// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8UBlu1x51bUiY7g2xg6WOCcGCLmfDqbQ',
    appId: '1:1008914227771:web:ef1eeeb52ed32431b9321e',
    messagingSenderId: '1008914227771',
    projectId: 'meetly-2k25',
    authDomain: 'meetly-2k25.firebaseapp.com',
    storageBucket: 'meetly-2k25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOeShcJmUIjZ5Rlo5Dx0iPv8q_H_WFFQg',
    appId: '1:1014329983101:android:75fdf805153b437624b114',
    messagingSenderId: '1014329983101',
    projectId: 'meetly-2k25-ed75a',
    storageBucket: 'meetly-2k25-ed75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjO3hnk3o-FJgYnn9iNZlSIiCyHFtBfk',
    appId: '1:1014329983101:ios:cf0434654f2a69f424b114',
    messagingSenderId: '1014329983101',
    projectId: 'meetly-2k25-ed75a',
    storageBucket: 'meetly-2k25-ed75a.firebasestorage.app',
    iosBundleId: 'com.example.meetly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS4ywe1czUNk65nxyP4J22z37hsdJxY6A',
    appId: '1:1008914227771:ios:11d82989af8012efb9321e',
    messagingSenderId: '1008914227771',
    projectId: 'meetly-2k25',
    storageBucket: 'meetly-2k25.firebasestorage.app',
    iosBundleId: 'com.example.meetly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8UBlu1x51bUiY7g2xg6WOCcGCLmfDqbQ',
    appId: '1:1008914227771:web:7c61f2e5c63f5db4b9321e',
    messagingSenderId: '1008914227771',
    projectId: 'meetly-2k25',
    authDomain: 'meetly-2k25.firebaseapp.com',
    storageBucket: 'meetly-2k25.firebasestorage.app',
  );
}